# Site settings
title: Mattux >> log
description: So contare fino a 31 usando una mano sola.
baseurl: "" 
url: "http://mattux.github.io" 
base_hostname: "mattux.github.io"
twitter_username: mtpani
github_username:  mattux
paginate: 4
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate

# Build settings
markdown: kramdown
