# Site settings
title: Mattux >> log
email:
description: > # this means to ignore newlines until "baseurl:"
  Di Linux, Open Source ed in teoria anche di Informatica.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _mattux_
github_username:  mattux

# Build settings
markdown: kramdown
